build_task: pipelines/gradle/tasks/gradle-assemble.yml # don't change
deploy_dev_task: pipelines/cf/tasks/blue-green-deploy.yml # don't change

app_name: roster 
jar_name: smichels-roster # set this to '<first_initial><lastname>-roster' ex: sgreenberg-roster

github_app_repo_uri: https://github.com/sam-michels/roster-gradle  # https url of your roster app github fork.  ex: https://github.com/spgreenberg/roster-gradle.git
github_app_repo_branch: master # don't change

github_pipelines_repo_uri: https://github.com/sam-michels/training-pipelines-initial
github_pipelines_repo_branch: master # don't change

version_bucket: rscale-training-bucket # don't change
version_bucket_region_name: us-west-2 # don't change

version_key: smichels-roster-version # set to '<first_initial><lastname>-roster-version'.  ex: sgreenberg-roster-version
initial_version: 0.0.1

artifact_regexp: smichels-roster-(.*).jar # set to '<first_initial><lastname>-roster-(.*).jar'.  ex: sgreenberg-roster-(.*).jar
artifact_bucket: rscale-training-bucket # don't change
artifact_bucket_region_name: us-west-2 # don't change

cf_dev_api: https://api.run.pivotal.io # set to cf api endpoint
cf_dev_organization: rscale-training-4 # set to your org
cf_dev_space: sam.michels@cgi.com # set to your space
cf_dev_hostname: roster-smichels # set to 'roster-<first_initial><lastname>'. ex: roster-sgreenberg
cf_dev_domain: cfapps.io # set to the apps domain for your CF
cf_dev_manifest: roster_manifest.yml # set to the dev manifest path in your roster app repository. ex: dev-manifest.yml
